name: Linux

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.txt']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', '**.txt']

env:
  proc_num: $(nproc)

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        mode: [dbg, opt]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux-${{ matrix.mode }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1

      - name: Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip clang-format-16 libibverbs-dev ccache python3-pyelftools libnuma-dev
          sudo ln -sf /usr/bin/clang-format-16 /usr/bin/clang-format
      
      - name: Format
        run: |
          git diff --exit-code

      - name: Build
        run: |
          bazel build -c ${{ matrix.mode }} --verbose_failures=true --jobs=${{env.proc_num}} //...
        env:
          CC: gcc-13
          CXX: g++-13
      
      - name: Test
        run: |
          echo 'Test'
